name: machine-learning-eldeskar

channels:
  - conda-forge
  - defaults

dependencies:
- python=3.10
- pip:
  - numpy
  - pandas
  - Scikit-learn
  - TensorFlow
  - Keras
  - PyTorch
  - Matplotlib
  - ydata-profiling
  - osmnx